=head1 What is Actium?

Actium is a project to release publicly some code and data used to
create public information materials for

L<AC Transit|http://www.actransit.org> (online timetables, printed
schedules at stops) using a series of Perl programs, Applescript
programs, FileMaker databases and  InDesign documents.

What's here now is (almost entirely) just the Perl programs, which I am
slowly reorganizing and rewriting. It is not ready yet for anybody else
to use, but perhaps those who are interested can at least see what it
looks like.

=head1 Why the name "actium"?

It was chosen because it is a word beginning with "ACT" (for "AC
Transit").  It is the name of peninsula in Greece; it gave its name to
an  important  L<battle|https://en.wikipedia.org/wiki/Battle_of_Actium>
that gave rise to the Roman Empire.

=head1 COPYRIGHT & LICENSE

Copyright 2011-2017

The Actium system is free software; you can redistribute it and/or
modify it under the terms of either:

* the GNU General Public License as published by the Free Software
Foundation; either version 1, or (at your option) any later version, or

* the Artistic License version 2.0.

This system is distributed in the hope that it will be useful, but
WITHOUT  ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or  FITNESS FOR A PARTICULAR PURPOSE.

