package Octium::StopReports 0.012;

use Actium;
use Octium;
use Params::Validate;

sub citiesbyline {

    my %params
      = validate( @_, { actiumdb => { can => 'each_row_eq' }, } );
    my $actiumdb = $params{actiumdb};

    my $eachstop = $actiumdb->each_columns_in_row_where(
        table   => 'Stops_Neue',
        columns => [qw/h_stp_511_id p_lines c_city/],
        where   => 'WHERE p_active = 1'
    );

    # build lines by city and type struct
    my %cities_of;
    while ( my $colref = $eachstop->() ) {
        \my @cols = $colref;
        my ( undef, $p_lines, $c_city ) = @cols;

        my @lines = split( /\s+/, $p_lines );
        foreach my $line (@lines) {
            $cities_of{$line}{$c_city} = 1;
        }
    }

    foreach my $line ( Actium::sortbyline keys %cities_of ) {

        my @cities = sort ( keys %{ $cities_of{$line} } );

        say $line;
        foreach my $city (@cities) {
            say "   $city";
        }
        say "";

    }

    return;

}    ## tidy end: sub citiesbyline

sub linesbycity {

    my %params
      = validate( @_, { actiumdb => { can => 'each_row_eq' }, } );

    my $actiumdb = $params{actiumdb};

    my %type_of;
    foreach my $line ( $actiumdb->line_keys ) {
        \my %row = $actiumdb->line_row_r($line);
        if ( Actium::feq( $row{agency_id}, 'ACTransit' ) ) {
            # note that is not agency name. Name has spaces.
            # ID does not
            $type_of{$line} = $row{LineGroupType};
        }
        else {
            $type_of{$line} = $EMPTY;
        }
    }

    #my $eachstop = $actiumdb->each_row_eq( 'Stops_Neue', 'p_active', '1' );

    my $eachstop = $actiumdb->each_columns_in_row_where(
        table   => 'Stops_Neue',
        columns => [qw/h_stp_511_id p_lines c_city/],
        where   => 'WHERE p_active = 1'
    );

    # build lines by city and type struct
    my %lines_of;
    while ( my $colref = $eachstop->() ) {
        \my @cols = $colref;
        my ( undef, $p_lines, $c_city ) = @cols;

        my @lines = split( ' ', $p_lines );
        foreach my $line (@lines) {
            my $type = $type_of{$line} // 'Local';
            $lines_of{$c_city}{$type}{$line} = 1;
        }
    }

    open my $html_fh, '>', \my $html_text
      or die "Can't open output to scalar: $OS_ERROR";

    print $html_fh "\n<!--\n    Do not edit this file! "
      . "It is automatically generated from a program.\n-->\n";

    my @all_lgtypes = $actiumdb->linegrouptypes_in_order;

    foreach my $city ( sort keys %lines_of ) {
        my $city_h = Actium::encode_entities($city);
        print $html_fh
          qq{<h4 style="text-transform:uppercase;" id="$city_h">$city_h</h4>};

        #        foreach my $type ( sort keys %{ $lines_of{$city} } ) {
        foreach my $type (@all_lgtypes) {
            next unless exists $lines_of{$city}{$type};
            my $type_h = Actium::encode_entities($type);
            print $html_fh "<p><strong>$type_h:</strong>";

            my @lines = Actium::sortbyline keys %{ $lines_of{$city}{$type} };

            foreach my $line (@lines) {
                my $url = $actiumdb->linesked_url($line);
                $line = qq{<a href="$url">$line</a>};
            }

            my $separator = '&nbsp;&nbsp;&nbsp; ';

            say $html_fh $separator, join( $separator, @lines ), '</p>';

        }
        #say $html_fh '</dl>';

    }    ## tidy end: foreach my $city ( sort keys...)

    return ( struct => \%lines_of, html => $html_text );

}    ## tidy end: sub linesbycity

1;

__END__

=encoding utf8

=head1 NAME

<name> - <brief description>

=head1 VERSION

This documentation refers to version 0.003

=head1 SYNOPSIS

 use <name>;
 # do something with <name>
   
=head1 DESCRIPTION

A full description of the module and its features.

=head1 SUBROUTINES or METHODS (pick one)

=over

=item B<subroutine()>

Description of subroutine.

=back

=head1 DIAGNOSTICS

A list of every error and warning message that the application can
generate (even the ones that will "never happen"), with a full
explanation of each problem, one or more likely causes, and any
suggested remedies. If the application generates exit status codes,
then list the exit status associated with each error.

=head1 CONFIGURATION AND ENVIRONMENT

A full explanation of any configuration system(s) used by the
application, including the names and locations of any configuration
files, and the meaning of any environment variables or properties that
can be se. These descriptions must also include details of any
configuration language used.

=head1 DEPENDENCIES

List its dependencies.

=head1 AUTHOR

Aaron Priven <apriven@actransit.org>

=head1 COPYRIGHT & LICENSE

Copyright 2017

This program is free software; you can redistribute it and/or modify it
under the terms of either:

=over 4

=item * the GNU General Public License as published by the Free
Software Foundation; either version 1, or (at your option) any
later version, or

=item * the Artistic License version 2.0.

=back

This program is distributed in the hope that it will be useful, but
WITHOUT  ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or  FITNESS FOR A PARTICULAR PURPOSE.

